<ul id="menu" class="page-sidebar-menu">

    <li {!! (Request::is('admin/users') || Request::is('admin/users/create') || Request::is('admin/users/*') ? 'class="active"' : '') !!}>
        <a href="{{ URL::to('admin/users') }}">
            <i class="livicon" data-name="user" data-size="18" data-c="#6CC66C" data-hc="#6CC66C"
               data-loop="true"></i>
            <span class="title">@lang('general.users')</span>
        </a>
    </li>

    <li {!! (Request::is('admin/broadcast') ||  Request::is('admin/broadcast/create') || Request::is('admin/broadcast/*') ? 'class="active"' : '') !!}>
        <a href="{{ URL::to('admin/broadcast') }}">
            <i class="livicon" data-name="film" data-c="#418BCA" data-hc="#418BCA" data-size="18"
               data-loop="true"></i>
            <span class="title">@lang('general.broadcast')</span>
        </a>
    </li>

    <li {!! (Request::is('admin/classify') || Request::is('admin/classify/create') || Request::is('admin/classify/*') ? 'class="active"' : '') !!}>
        <a href="{{ URL::to('admin/classify') }}">
            <i class="livicon" data-name="help" data-c="#ef6f6c" data-hc="#ef6f6c" data-size="18"
               data-loop="true"></i>
            <span class="title">@lang('general.classify')</span>
        </a>
    </li>

    <li {!! (Request::is('admin/country') || Request::is('admin/country/create') || Request::is('admin/country/*') ? 'class="active"' : '') !!}>
        <a href="{{ URL::to('admin/country') }}">
            <i class="livicon" data-name="globe" data-c="#fff" data-hc="#fff" data-size="18"
               data-loop="true"></i>
            <span class="title">@lang('general.country')</span>
        </a>
    </li>

    <li {!! (Request::is('admin/transaction') || Request::is('admin/transaction/*') ? 'class="active"' : '') !!}>
        <a href="{{ URL::to('admin/transaction') }}">
            <i class="livicon" data-name="money" data-c="#018d69" data-hc="#018d69" data-size="18"
               data-loop="true"></i>
            <span class="title">@lang('general.transaction')</span>
        </a>
    </li>
    <!-- Menus generated by CRUD generator -->
    @include('admin/layouts/menu')
</ul>
